<?php
/**
 * The plan -> feature matrix.
 *
 * GENERATED by wp/bin/build-admin-kit.php from docs/plugins-overhaul/features.json and
 * wp/packages/zinn-admin-kit/data/plans.json. Never edit: `--check` refuses a copy that differs.
 * A feature's plan changes in those two files, and nowhere else.
 *
 * @package ZinnDigital\Tranzly\AdminKit
 */

declare( strict_types = 1 );

namespace ZinnDigital\Tranzly\AdminKit;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Which plan each feature needs, and the translated names the plan comparison shows.
 */
final class Matrix {

	/** Feature id => the lowest plan that includes it. */
	public const MIN_PLAN = array(
		'tz-f1'   => 'free',
		'tz-f2'   => 'free',
		'tz-f3'   => 'free',
		'tz-f4'   => 'free',
		'tz-f5'   => 'free',
		'tz-f6'   => 'free',
		'tz-f7'   => 'free',
		'tz-e1'   => 'free',
		'tz-e2'   => 'free',
		'tz-e3'   => 'personal',
		'tz-e4'   => 'personal',
		'tz-e5'   => 'personal',
		'tz-e6'   => 'free',
		'tz-e7'   => 'personal',
		'tz-e8'   => 'personal',
		'tz-e9'   => 'personal',
		'tz-c1'   => 'free',
		'tz-c2'   => 'free',
		'tz-c3'   => 'free',
		'tz-c4'   => 'free',
		'tz-c5'   => 'free',
		'tz-c6'   => 'personal',
		'tz-c7'   => 'personal',
		'tz-c8'   => 'personal',
		'tz-c9'   => 'personal',
		'tz-c10'  => 'personal',
		'tz-c11'  => 'free',
		'tz-c12'  => 'personal',
		'tz-c13'  => 'free',
		'tz-w1'   => 'free',
		'tz-w2'   => 'personal',
		'tz-w3'   => 'personal',
		'tz-w4'   => 'free',
		'tz-w5'   => 'personal',
		'tz-w6'   => 'personal',
		'tz-w7'   => 'personal',
		'tz-w8'   => 'personal',
		'tz-w9'   => 'free',
		'tz-s1'   => 'free',
		'tz-s2'   => 'personal',
		'tz-s3'   => 'free',
		'tz-s4'   => 'free',
		'tz-s5'   => 'free',
		'tz-s6'   => 'free',
		'tz-s7'   => 'personal',
		'tz-s8'   => 'free',
		'tz-l1'   => 'free',
		'tz-l2'   => 'free',
		'tz-l3'   => 'personal',
		'tz-l4'   => 'free',
		'tz-l5'   => 'free',
		'tz-l6'   => 'free',
		'tz-dev1' => 'free',
		'tz-dev2' => 'free',
		'tz-dev3' => 'free',
		'tz-dev4' => 'personal',
		'ai-1'    => 'free',
		'ai-2'    => 'free',
		'ai-3'    => 'free',
		'ai-4'    => 'free',
		'ai-5'    => 'free',
		'ai-6'    => 'free',
		'ai-7'    => 'free',
		'ai-8'    => 'personal',
		'ai-9'    => 'personal',
		'ai-10'   => 'free',
		'adm-1'   => 'free',
		'adm-2'   => 'free',
		'adm-3'   => 'free',
		'adm-4'   => 'free',
		'adm-5'   => 'free',
		'adm-6'   => 'free',
		'adm-7'   => 'personal',
		'adm-8'   => 'personal',
		'adm-9'   => 'free',
		'adm-10'  => 'free',
		'tz-r1'   => 'free',
		'tz-r2'   => 'free',
		'tz-r3'   => 'free',
		'tz-r4'   => 'free',
		'tz-r5'   => 'personal',
		'tz-r6'   => 'personal',
		'tz-r7'   => 'free',
		'tz-r8'   => 'personal',
		'tz-r9'   => 'personal',
		'tz-r10'  => 'personal',
		'tz-r11'  => 'personal',
		'tz-r12'  => 'personal',
		'tz-r13'  => 'free',
		'tz-r14'  => 'free',
		'tz-r15'  => 'agency',
		'sh-r1'   => 'personal',
		'sh-r2'   => 'free',
		'sh-r3'   => 'free',
		'sh-r4'   => 'free',
		'sh-r5'   => 'business',
		'sh-r6'   => 'free',
		'sh-r7'   => 'free',
		'sh-r8'   => 'free',
	);

	/** Feature id => array( area index, shown in the plan comparison ). */
	public const ROWS = array(
		'tz-f1'   => array( 0, true ),
		'tz-f2'   => array( 0, true ),
		'tz-f3'   => array( 0, true ),
		'tz-f4'   => array( 0, true ),
		'tz-f5'   => array( 0, true ),
		'tz-f6'   => array( 0, true ),
		'tz-f7'   => array( 0, true ),
		'tz-e1'   => array( 1, true ),
		'tz-e2'   => array( 1, true ),
		'tz-e3'   => array( 1, true ),
		'tz-e4'   => array( 1, true ),
		'tz-e5'   => array( 1, true ),
		'tz-e6'   => array( 1, true ),
		'tz-e7'   => array( 1, true ),
		'tz-e8'   => array( 1, true ),
		'tz-e9'   => array( 1, true ),
		'tz-c1'   => array( 2, true ),
		'tz-c2'   => array( 2, true ),
		'tz-c3'   => array( 2, true ),
		'tz-c4'   => array( 2, true ),
		'tz-c5'   => array( 2, true ),
		'tz-c6'   => array( 2, true ),
		'tz-c7'   => array( 2, true ),
		'tz-c8'   => array( 2, true ),
		'tz-c9'   => array( 2, true ),
		'tz-c10'  => array( 2, true ),
		'tz-c11'  => array( 2, true ),
		'tz-c12'  => array( 2, true ),
		'tz-c13'  => array( 2, true ),
		'tz-w1'   => array( 3, true ),
		'tz-w2'   => array( 3, true ),
		'tz-w3'   => array( 3, true ),
		'tz-w4'   => array( 3, true ),
		'tz-w5'   => array( 3, true ),
		'tz-w6'   => array( 3, true ),
		'tz-w7'   => array( 3, true ),
		'tz-w8'   => array( 3, true ),
		'tz-w9'   => array( 3, true ),
		'tz-s1'   => array( 4, true ),
		'tz-s2'   => array( 4, true ),
		'tz-s3'   => array( 4, true ),
		'tz-s4'   => array( 4, true ),
		'tz-s5'   => array( 4, true ),
		'tz-s6'   => array( 4, true ),
		'tz-s7'   => array( 4, true ),
		'tz-s8'   => array( 4, true ),
		'tz-l1'   => array( 5, true ),
		'tz-l2'   => array( 5, true ),
		'tz-l3'   => array( 5, true ),
		'tz-l4'   => array( 5, true ),
		'tz-l5'   => array( 5, true ),
		'tz-l6'   => array( 5, true ),
		'tz-dev1' => array( 6, true ),
		'tz-dev2' => array( 6, true ),
		'tz-dev3' => array( 6, true ),
		'tz-dev4' => array( 6, true ),
		'ai-1'    => array( 7, true ),
		'ai-2'    => array( 7, true ),
		'ai-3'    => array( 7, true ),
		'ai-4'    => array( 7, true ),
		'ai-5'    => array( 7, true ),
		'ai-6'    => array( 7, true ),
		'ai-7'    => array( 7, true ),
		'ai-8'    => array( 7, true ),
		'ai-9'    => array( 7, true ),
		'ai-10'   => array( 7, true ),
		'adm-1'   => array( 8, true ),
		'adm-2'   => array( 8, true ),
		'adm-3'   => array( 8, true ),
		'adm-4'   => array( 8, false ),
		'adm-5'   => array( 8, false ),
		'adm-6'   => array( 8, false ),
		'adm-7'   => array( 8, true ),
		'adm-8'   => array( 8, true ),
		'adm-9'   => array( 8, false ),
		'adm-10'  => array( 8, false ),
		'tz-r1'   => array( 9, true ),
		'tz-r2'   => array( 9, true ),
		'tz-r3'   => array( 9, true ),
		'tz-r4'   => array( 9, true ),
		'tz-r5'   => array( 9, true ),
		'tz-r6'   => array( 9, true ),
		'tz-r7'   => array( 9, true ),
		'tz-r8'   => array( 9, true ),
		'tz-r9'   => array( 9, true ),
		'tz-r10'  => array( 9, true ),
		'tz-r11'  => array( 9, true ),
		'tz-r12'  => array( 9, true ),
		'tz-r13'  => array( 9, true ),
		'tz-r14'  => array( 9, true ),
		'tz-r15'  => array( 9, true ),
		'sh-r1'   => array( 10, true ),
		'sh-r2'   => array( 10, true ),
		'sh-r3'   => array( 10, true ),
		'sh-r4'   => array( 10, true ),
		'sh-r5'   => array( 10, true ),
		'sh-r6'   => array( 10, true ),
		'sh-r7'   => array( 10, false ),
		'sh-r8'   => array( 10, true ),
	);

	/**
	 * The lowest plan that includes a feature, or null for an unknown id.
	 *
	 * @param string $feature Feature id.
	 * @return string|null
	 */
	public static function min_plan( string $feature ): ?string {
		return self::MIN_PLAN[ $feature ] ?? null;
	}

	/**
	 * The plans, lowest first, with their site limits (null = unlimited).
	 *
	 * @return array<int, array{id: string, sites: int|null}>
	 */
	public static function plans(): array {
		return array(
			array(
				'id'    => 'free',
				'sites' => null,
			),
			array(
				'id'    => 'personal',
				'sites' => 1,
			),
			array(
				'id'    => 'business',
				'sites' => 5,
			),
			array(
				'id'    => 'agency',
				'sites' => null,
			),
		);
	}

	/**
	 * Feature names, translated.
	 *
	 * @return array<string, string>
	 */
	public static function titles(): array {
		return array(
			'tz-f1'   => __( 'One post per language, linked together', 'tranzly' ),
			'tz-f2'   => __( 'Keeps your old Tranzly translations', 'tranzly' ),
			'tz-f3'   => __( 'Translate in the background', 'tranzly' ),
			'tz-f4'   => __( 'Latest WordPress and PHP, tested every release', 'tranzly' ),
			'tz-f5'   => __( 'Security by design', 'tranzly' ),
			'tz-f6'   => __( 'Interface in 58 languages, right-to-left ready', 'tranzly' ),
			'tz-f7'   => __( 'Unlimited languages', 'tranzly' ),
			'tz-e1'   => __( 'DeepL (the current integration, kept)', 'tranzly' ),
			'tz-e2'   => __( 'AI models with your own key', 'tranzly' ),
			'tz-e3'   => __( 'Google Cloud Translation and Microsoft Translator', 'tranzly' ),
			'tz-e4'   => __( 'Different engine per language', 'tranzly' ),
			'tz-e5'   => __( 'Automatic fallback', 'tranzly' ),
			'tz-e6'   => __( 'Cost estimate before you start', 'tranzly' ),
			'tz-e7'   => __( 'Translation memory', 'tranzly' ),
			'tz-e8'   => __( 'Glossary and do-not-translate list for every engine', 'tranzly' ),
			'tz-e9'   => __( 'Tone and style instructions', 'tranzly' ),
			'tz-c1'   => __( 'Posts, pages and custom post types', 'tranzly' ),
			'tz-c2'   => __( 'Blocks translated safely', 'tranzly' ),
			'tz-c3'   => __( 'Categories, tags and custom taxonomies', 'tranzly' ),
			'tz-c4'   => __( 'Menus', 'tranzly' ),
			'tz-c5'   => __( 'Page Builder Sandwich pages', 'tranzly' ),
			'tz-c6'   => __( 'Elementor, Bricks, Divi, Beaver Builder, Oxygen and WPBakery', 'tranzly' ),
			'tz-c7'   => __( 'WooCommerce: everything', 'tranzly' ),
			'tz-c8'   => __( 'SEO fields for all four big SEO plugins', 'tranzly' ),
			'tz-c9'   => __( 'Custom fields', 'tranzly' ),
			'tz-c10'  => __( 'Theme and plugin text (strings)', 'tranzly' ),
			'tz-c11'  => __( 'Media', 'tranzly' ),
			'tz-c12'  => __( 'Block themes: templates and patterns', 'tranzly' ),
			'tz-c13'  => __( 'Widgets and site title/tagline', 'tranzly' ),
			'tz-w1'   => __( 'Translate one post in one click', 'tranzly' ),
			'tz-w2'   => __( 'Bulk translate the whole site', 'tranzly' ),
			'tz-w3'   => __( 'Auto-translate new and updated content', 'tranzly' ),
			'tz-w4'   => __( 'Side-by-side translation editor', 'tranzly' ),
			'tz-w5'   => __( 'Visual front-end editor', 'tranzly' ),
			'tz-w6'   => __( 'Review and approval', 'tranzly' ),
			'tz-w7'   => __( 'Export and import for human translators', 'tranzly' ),
			'tz-w8'   => __( 'Switch from WPML, Polylang or TranslatePress', 'tranzly' ),
			'tz-w9'   => __( 'Translation status dashboard', 'tranzly' ),
			'tz-s1'   => __( 'Language in the URL: /de/, /fr/', 'tranzly' ),
			'tz-s2'   => __( 'Subdomains or separate domains per language', 'tranzly' ),
			'tz-s3'   => __( 'Translated slugs', 'tranzly' ),
			'tz-s4'   => __( 'hreflang tags, done right', 'tranzly' ),
			'tz-s5'   => __( 'Translated sitemaps', 'tranzly' ),
			'tz-s6'   => __( 'Correct language and canonical tags', 'tranzly' ),
			'tz-s7'   => __( 'Hide untranslated pages from search engines', 'tranzly' ),
			'tz-s8'   => __( 'Suggest the visitor\'s language', 'tranzly' ),
			'tz-l1'   => __( 'Switcher block for the block editor', 'tranzly' ),
			'tz-l2'   => __( 'Switcher element for Page Builder Sandwich', 'tranzly' ),
			'tz-l3'   => __( 'Switcher for Elementor, Bricks and other builders', 'tranzly' ),
			'tz-l4'   => __( 'Menu item, widget and shortcode', 'tranzly' ),
			'tz-l5'   => __( 'Floating switcher', 'tranzly' ),
			'tz-l6'   => __( 'Accessible switcher', 'tranzly' ),
			'tz-dev1' => __( 'PHP API and template functions', 'tranzly' ),
			'tz-dev2' => __( 'Add your own translation engine', 'tranzly' ),
			'tz-dev3' => __( 'Hooks, REST API and WP-CLI', 'tranzly' ),
			'tz-dev4' => __( 'Compatibility layer for Polylang/WPML functions', 'tranzly' ),
			'ai-1'    => __( 'Bring your own key for all main AI providers', 'tranzly' ),
			'ai-2'    => __( 'Model list updates itself', 'tranzly' ),
			'ai-3'    => __( 'We push recommended models in updates', 'tranzly' ),
			'ai-4'    => __( 'Add a model yourself in one step', 'tranzly' ),
			'ai-5'    => __( 'Simple setup for non-technical users', 'tranzly' ),
			'ai-6'    => __( 'Keys stored encrypted, never sent to us', 'tranzly' ),
			'ai-7'    => __( 'Clear error messages', 'tranzly' ),
			'ai-8'    => __( 'Usage and cost log', 'tranzly' ),
			'ai-9'    => __( 'Per-role AI permissions', 'tranzly' ),
			'ai-10'   => __( 'One key, both plugins', 'tranzly' ),
			'adm-1'   => __( 'Modern admin screens', 'tranzly' ),
			'adm-2'   => __( 'Setup wizard', 'tranzly' ),
			'adm-3'   => __( 'Built-in help', 'tranzly' ),
			'adm-4'   => __( 'Cross-promotion between the two plugins', 'tranzly' ),
			'adm-5'   => __( 'Zinn Digital® hosting promotion', 'tranzly' ),
			'adm-6'   => __( 'Pro licensing through Freemius (latest SDK)', 'tranzly' ),
			'adm-7'   => __( 'Free trial of Pro', 'tranzly' ),
			'adm-8'   => __( 'Bundle: Page Builder Sandwich Pro + Tranzly Pro', 'tranzly' ),
			'adm-9'   => __( 'Credited to Zinn Digital® Ltd', 'tranzly' ),
			'adm-10'  => __( 'Synced to GitHub like our other plugins', 'tranzly' ),
			'tz-r1'   => __( 'Manual edits are protected', 'tranzly' ),
			'tz-r2'   => __( 'Failed translation report', 'tranzly' ),
			'tz-r3'   => __( 'Edit any translation easily', 'tranzly' ),
			'tz-r4'   => __( 'Do-not-translate list in the free version', 'tranzly' ),
			'tz-r5'   => __( 'WooCommerce multi-currency', 'tranzly' ),
			'tz-r6'   => __( 'AI quality check', 'tranzly' ),
			'tz-r7'   => __( 'Show content only in some languages', 'tranzly' ),
			'tz-r8'   => __( 'Multilingual SEO audit', 'tranzly' ),
			'tz-r9'   => __( 'Translate forms', 'tranzly' ),
			'tz-r10'  => __( 'Translate comments and reviews', 'tranzly' ),
			'tz-r11'  => __( 'Different images per language', 'tranzly' ),
			'tz-r12'  => __( 'Monthly spend cap per engine', 'tranzly' ),
			'tz-r13'  => __( 'Multilingual site search', 'tranzly' ),
			'tz-r14'  => __( 'Speed promise, tested', 'tranzly' ),
			'tz-r15'  => __( 'Multisite support', 'tranzly' ),
			'sh-r1'   => __( 'Staging and local sites don\'t use up a licence', 'tranzly' ),
			'sh-r2'   => __( 'Docs site and short video guides', 'tranzly' ),
			'sh-r3'   => __( 'Feedback and feature-request button', 'tranzly' ),
			'sh-r4'   => __( 'Beta updates channel', 'tranzly' ),
			'sh-r5'   => __( 'Priority support', 'tranzly' ),
			'sh-r6'   => __( 'Bug reporter and support tickets', 'tranzly' ),
			'sh-r7'   => __( 'Use Freemius fully', 'tranzly' ),
			'sh-r8'   => __( 'Footprint-free front end, on by default', 'tranzly' ),
		);
	}

	/**
	 * Area names, translated, by index.
	 *
	 * @return array<int, string>
	 */
	public static function areas(): array {
		return array(
			0  => __( 'Foundation', 'tranzly' ),
			1  => __( 'Translation engines', 'tranzly' ),
			2  => __( 'What gets translated', 'tranzly' ),
			3  => __( 'Workflow', 'tranzly' ),
			4  => __( 'SEO and URLs', 'tranzly' ),
			5  => __( 'Language switcher', 'tranzly' ),
			6  => __( 'Developers', 'tranzly' ),
			7  => __( 'AI keys and models', 'tranzly' ),
			8  => __( 'Admin and licensing', 'tranzly' ),
			9  => __( 'More features', 'tranzly' ),
			10 => __( 'Licensing and support', 'tranzly' ),
		);
	}

	/**
	 * The matrix as the admin shell reads it.
	 *
	 * @return array<int, array{id: string, area: string, title: string, min: string, compare: bool}>
	 */
	public static function for_js(): array {
		$titles = self::titles();
		$areas  = self::areas();
		$out    = array();
		foreach ( self::ROWS as $id => $row ) {
			$out[] = array(
				'id'      => $id,
				'area'    => $areas[ $row[0] ] ?? '',
				'title'   => $titles[ $id ] ?? $id,
				'min'     => self::MIN_PLAN[ $id ],
				'compare' => $row[1],
			);
		}

		return $out;
	}
}
